-- Script de creación de la tabla PRICES.
-- Se ha añadido una columna ID para identificar cada fila y que se pueda usar como clave

CREATE TABLE PRICES (
ID NUMERIC(20, 0) PRIMARY KEY,
BRAND_ID NUMERIC(20, 0) NOT NULL,
PRODUCT_ID NUMERIC(20, 0) NOT NULL,
START_DATE TIMESTAMP NOT NULL,
END_DATE TIMESTAMP NOT NULL,
PRIORITY NUMERIC(10,0) NOT NULL,
PRICE NUMERIC(7, 2) NOT NULL,
CURRENCY VARCHAR(40) NOT NULL,
PRICE_LIST NUMERIC(10, 0) NOT NULL
);

